Feature: Edit_Profile
    @javascript
    Scenario: Edit Profile
        Given I am logged in as the user "admin" with password "Password1"
        When I click on "link=Content" "named"
        Then I should see the element "//input[@id='profileform_firstname']" "xpath"
        When I fill in "#profileform_firstname" "css" with "Administrator"
        When I fill in "#profileform_lastname" "css" with "User Admin"
        When I fill in "#profileform_studentid" "css" with "1234"
        Then I should see the element "#profileform_preferredname" "css"
        When I fill in "#profileform_preferredname" "css" with "Admin User"
        When I click on "link=Contact information(tab)" "named"
        Then I should see the element "//a[@id=&quot;contact_a&quot; and @class=&quot;current-tab&quot;]" "xpath"
        When I click on "link=Add email address" "named"
        When I fill in "//div[@id='email_list']/div[2]/input" "xpath" with "cri@catalyst.net.nz"
        When I click on "//input[@value='Add']" "xpath"
        Then I should see the element "#profileform_officialwebsite" "css"
        When I fill in "#profileform_officialwebsite" "css" with "www.catalyst.net.nz"
        Then I should see the element "#profileform_personalwebsite" "css"
        When I fill in "#profileform_personalwebsite" "css" with "www.stuff.co.nz"
        Then I should see the element "#profileform_blogaddress" "css"
        When I fill in "#profileform_blogaddress" "css" with "www.blog.com"
        When I fill in "#profileform_address" "css" with "150 Willis Street"
        When I fill in "#profileform_city" "css" with "CBD"
        When I fill in "#profileform_homenumber" "css" with "04928375"
        When I fill in "#profileform_businessnumber" "css" with "040298375"
        When I fill in "#profileform_mobilenumber" "css" with "0272093875482"
        Then I should see the element "#profileform_faxnumber" "css"
        When I fill in "#profileform_faxnumber" "css" with "09237842"
        When I click on "#general_a" "css"
        Then I should see the element "#profileform_occupation" "css"
        When I fill in "#profileform_occupation" "css" with "it"
        Then I should see the element "#profileform_industry" "css"
        When I fill in "#profileform_industry" "css" with "it"
        Then I should see the element "#profileform_submit" "css"
        When I click on "#profileform_submit" "css"
        Then I should see not "regexp:Processing.*" in the element "#profileform_submit" "css"
        Then I should see the element "#footer-nav" "css"
        Then I should see the element "#messaging_a" "css"
        When I click on "#messaging_a" "css"
        Then I should see the element "//a[@id=&quot;messaging_a&quot; and @class=&quot;current-tab&quot;]" "xpath"
        Then I should see the element "#profileform_icqnumber" "css"
        When I fill in "#profileform_icqnumber" "css" with "923854"
        Then I should see the element "#profileform_msnnumber" "css"
        When I fill in "#profileform_msnnumber" "css" with "admin"
        Then I should see the element "#profileform_aimscreenname" "css"
        When I fill in "#profileform_aimscreenname" "css" with "admin"
        Then I should see the element "#profileform_yahoochat" "css"
        When I fill in "#profileform_yahoochat" "css" with "admin"
        Then I should see the element "#profileform_submit" "css"
        When I click on "#profileform_submit" "css"
        Then I should see not "regexp:Processing.*" in the element "#profileform_submit" "css"
        Then I should see the element "#footer-nav" "css"
        Then I should see the element "#messaging_a" "css"
        When I click on "#messaging_a" "css"
        Then I should see the element "//a[@id=&quot;messaging_a&quot; and @class=&quot;current-tab&quot;]" "xpath"
        When I click on "#contact_a" "css"
        Then I should see the element "//a[@id=&quot;contact_a&quot; and @class=&quot;current-tab&quot;]" "xpath"
        Then I should see "regexp:cri@catalyst.net.nz.*" in the element "//div[@id='email_list']/div[@class=&quot;unvalidated&quot;]" "xpath"